In [1]:
import tensorflow as tf

hello = tf.constant("Hello, Tensorflow!")
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [2]:
a = tf.constant(0)
b = tf.constant(32)
c = tf.add(a, b)
print(c)

Tensor("Add:0", shape=(), dtype=int32)


In [4]:
sess = tf.Session()
print(sess.run(hello))
print(sess.run([a, b, c]))
sess.close()

b'Hello, Tensorflow!'
[0, 32, 32]


In [5]:
X = tf.placeholder(tf.float32, [None, 3])
print(X)

Tensor("Placeholder:0", shape=(?, 3), dtype=float32)


In [6]:
x_data = [[1, 2, 3], [4, 5, 6]]

In [7]:
x_data

[[1, 2, 3], [4, 5, 6]]

In [8]:
W = tf.Variable(tf.random_normal([3, 2]))
b = tf.Variable(tf.random_normal([2, 1]))
expr = tf.matmul(X, W) + b

In [9]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

print("--- x_data ---")
print(x_data)
print("--- W ---")
print(sess.run(W))
print("--- b ---")
print(sess.run(b))
print("--- expr ---")
print(sess.run(expr, feed_dict={X: x_data}))

sess.close()

--- x_data ---
[[1, 2, 3], [4, 5, 6]]
--- W ---
[[ 0.9139254  -0.48288065]
 [ 0.36753356  0.18717353]
 [ 0.5170133   0.11286841]]
--- b ---
[[-0.2825155]
 [ 1.0383618]]
--- expr ---
[[ 2.917517   -0.05244386]
 [ 9.633811    0.7199173 ]]
